# Generated by Django 4.1.3 on 2022-11-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times", models.IntegerField(blank=True, verbose_name="次")),
                ("score", models.IntegerField(verbose_name="分数")),
            ],
            options={
                "verbose_name": "分数",
                "verbose_name_plural": "分数",
                "ordering": ["times"],
            },
        ),
    ]
