# Generated by Django 4.1.3 on 2022-11-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(blank=True, verbose_name="分数"),
        ),
        migrations.AlterField(
            model_name="score",
            name="times",
            field=models.IntegerField(blank=True, verbose_name="次序"),
        ),
    ]
