# Generated by Django 4.1.3 on 2022-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0003_alter_score_score_alter_score_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="score",
            options={
                "ordering": ["times"],
                "verbose_name": "分数",
                "verbose_name_plural": "分数",
            },
        ),
        migrations.AlterField(
            model_name="score",
            name="times",
            field=models.IntegerField(blank=True, verbose_name="次"),
        ),
    ]
