# Generated by Django 4.1.3 on 2022-11-13 06:58

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvancedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=128, verbose_name="题目")),
                ("order", models.BooleanField(default=True, verbose_name="选项正序")),
                (
                    "qid",
                    models.IntegerField(
                        blank=True, default=question.models.aqids, verbose_name="题号"
                    ),
                ),
            ],
            options={
                "verbose_name": "进阶题库",
                "verbose_name_plural": "进阶题库",
            },
        ),
        migrations.CreateModel(
            name="BasicQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=128, verbose_name="题目")),
                ("order", models.BooleanField(default=True, verbose_name="选项正序")),
                (
                    "qid",
                    models.IntegerField(
                        blank=True, default=question.models.qids, verbose_name="题号"
                    ),
                ),
            ],
            options={
                "verbose_name": "基础题库",
                "verbose_name_plural": "基础题库",
            },
        ),
    ]
