# Generated by Django 4.1.3 on 2022-11-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="题号",
                    ),
                ),
                ("question", models.CharField(max_length=128, verbose_name="题目")),
                ("order", models.BooleanField(default=True, verbose_name="选项正序")),
            ],
            options={
                "verbose_name": "题库",
                "verbose_name_plural": "题库",
            },
        ),
    ]
