# Generated by Django 4.1.3 on 2022-11-08 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="favicon/%Y/%m/%d/"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("m", "男"), ("f", "女")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("contact", models.CharField(blank=True, max_length=128, null=True)),
                ("area", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
