# Generated by Django 4.1.3 on 2022-11-10 15:46

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=info.models.rename_picture,
                verbose_name="头像",
            ),
        ),
    ]
