# Generated by Django 4.1.3 on 2022-11-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="info",
            options={"verbose_name": "用户信息", "verbose_name_plural": "用户信息"},
        ),
    ]
