# Generated by Django 4.1.3 on 2022-11-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_alter_info_area_alter_info_contact_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="user",
            new_name="user_id",
        ),
    ]
