# Generated by Django 4.1.3 on 2022-11-07 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=32, verbose_name="密码哈希")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="favicon/%Y/%m/%d/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("m", "男"), ("f", "女")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(default=datetime.date.today, verbose_name="生日"),
                ),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=500, verbose_name="简介"),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=20, verbose_name="联系方式"),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=20, verbose_name="地区"),
                ),
            ],
        ),
    ]
