# Generated by Django 4.1.3 on 2022-11-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户账号", "verbose_name_plural": "用户账号"},
        ),
    ]
